image: maven:latest
variables:
  SONAR_TOKEN: "d5afef7acedb25222aa740678c2e478cf348b268"
  SONAR_HOST_URL: "https://sonarcloud.io"
  GIT_DEPTH: 0

sonarcloud-backend-jobs-microservice:
  stage: sonar-jobs
  script:
    - cd "${CI_PROJECT_DIR}/Backend/jobs-microservice"
    - mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=jobs-microservice -Dsonar.login=d5afef7acedb25222aa740678c2e478cf348b268 -Dsonar.organization=mohammed-sameeruddin
      -Dsonar.qualitygate.wait=true
  allow_failure: true
  only:
    - merge_requests
    - main
