server:
  port: 9005

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: SKILL-SERVICE
          uri: lb://SKILL-SERVICE
          predicates:
            - Path=/skills/**
        - id: ROUTE-SERVICE
          uri: lb://ROUTE-SERVICE
          predicates:
            - Path=/routes/**
        - id: LOCATION-SERVICE
          uri: lb://LOCATION-SERVICE
          predicates:
            - Path=/location/**
        - id: JOB-SERVICE
          uri: lb://JOB-SERVICE
          predicates:
            - Path=/jobs/**
        - id: SEARCH-SERVICE
          uri: lb://JOB-SERVICE
          predicates:
            - Path=/search/**



eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://18.223.206.231:9006/eureka/
  instance:
    hostname: 18.223.206.231